set schema public;

drop table IF EXISTS RECIPES;
drop table IF EXISTS INGREDIENTS;

create table RECIPES (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(500) NOT NULL
);

CREATE UNIQUE INDEX IF NOt EXISTS UNIQUE_RECIPE ON RECIPES(name);

create table INGREDIENTS (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    product VARCHAR(200) NOT NULL,
    amount VARCHAR(100) NOT NULL,
    RECIPES_ID INT
);